[project]
name = "mute-button"
version = "0.0.0"
description = "Make annoying people shut up"
dependencies = [
    "pyaudiowpatch>=0.2.12.7",
    "reflex>=0.8.0",
    "reflex-dynoselect>=0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
